@startuml
hide circle
skinparam shadowing false


title movement and Dialog Class Diagram
legend left
	Created by: Arthur Putnam
	Reviewed: 

	External Classes: Player

	
endlegend



class GameTile {

#Content
+set(int x, int y)
+AddContent(Content c)
+Content GetContent()

}
class Grid {
-<<GameTiles>> map
+setTile(GameTile t, int x, int y)
+getTile()
+display()

}

class Area {
-Grid
-<player> Players 
+Boolean move(int PlayerID, Location L)

}

class Location{
#int pos_x
#int pos_y
+int getX()
+int getY()
+setX(int x)
+setY(int y)
}

class Player{
<external>
}

Area -> Grid
Grid -> GameTile
Area -> Player
GameTile --|> Location






class Dialog {
	-<Messages> messages 
	+receive(Message m)
+display()

}
note top: A ordered set of messages\nthat can be added to and displayed
class Message {
	-String content
-String from
..Getters..
+getContent()
+getFrom()
..Setters..
+setContent(String message)
+setFrom(string user)

}

Dialog -> Message


@enduml
